import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mind Mosaic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="h-screen w-full">
            <div className="bg-overlay"></div>
            <div className="content-wrapper">
              <Header />
              <Toaster position="bottom-right" />
              <div>{children}</div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
